From 52f8fd2010b900c7d382a7c4e6c1a317d8160585 Mon Sep 17 00:00:00 2001
From: Hongxu Jia <hongxu.jia@windriver.com>
Date: Fri, 10 May 2019 14:30:36 +0800
Subject: [PATCH 2/7] gpgme/lang/python: gpg-error-config should not be used

gpg-error-config was modified by OE to always return an error.
So we want to find an alternative way to retrieve whatever it
is we need.

Upstream-Status: Inappropriate [changes are specific to OE]

Signed-off-by: Mark Hatle <mark.hatle@windriver.com>

Rebase to 1.13.0

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
---
 lang/python/setup.py.in | 9 +--------
 1 file changed, 1 insertion(+), 8 deletions(-)

diff --git a/lang/python/setup.py.in b/lang/python/setup.py.in
index 9785a28..006216d 100755
--- a/lang/python/setup.py.in
+++ b/lang/python/setup.py.in
@@ -30,7 +30,6 @@ import subprocess
 import sys
 
 # Out-of-tree build of the gpg bindings.
-gpg_error_config = ['gpg-error-config']
 gpgme_config_flags = ['--thread=pthread']
 gpgme_config = ['gpgme-config'] + gpgme_config_flags
 gpgme_h = ''
@@ -182,15 +181,9 @@ class BuildExtFirstHack(build):
 
     def _generate_errors_i(self):
 
-        try:
-            subprocess.check_call(
-                gpg_error_config + ['--version'], stdout=devnull)
-        except:
-            sys.exit('Could not find gpg-error-config.  ' +
-                     'Please install the libgpg-error development package.')
 
         gpg_error_content = self._read_header(
-            'gpg-error.h', getconfig('cflags', config=gpg_error_config))
+            "gpg-error.h", os.environ.get('CFLAGS').split())
 
         filter_re = re.compile(r'GPG_ERR_[^ ]* =')
         rewrite_re = re.compile(r' *(.*) = .*')
-- 
2.7.4

